### ISSUE TITLE
Replace top menu with side nav

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/druid#297]
<img width="812" alt="Screen Shot 2022-06-26 at 6 17 44 PM" src="https://user-images.githubusercontent.com/73197190/175836561-b4bff345-b961-4c46-afd2-1a0dcd0b9428.png">

**Comment by windbeneathyourwings** [comment]
This is the real time application of the design to editor. I think I really like where this is heading. Still need to add login button of some kind and quick search by path for now. Could also do name. I think the search just needs to be in-memory for now.
